# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  - job: CreateVM
  displayName: Create VM image
  dependsOn: Build
  condition: succeeded()
  pool:
    name: 'Google Cloud'
  variables:
    Packer.Project: '[Data_Insights]'
    Packer.Zone: '[us-central1-a]'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: '$(artifactName)'
  - task: CmdLine@1
    displayName: 'Publish artifact to Cloud Storage'
    inputs:
      filename: gsutil
      arguments: 'cp $(System.ArtifactsDirectory)\$(artifactName)\Orchard.Web.zip gs://$(Packer.Project)-artifacts/Orchard.Web-$(Build.BuildId).zip'
  - task: CmdLine@1
    displayName: 'Create image'
    inputs:
      filename: packer
      arguments: 'build -var "gcp_project=$(Packer.Project)" -var "gcp_zone=$(Packer.Zone)" -var "image_family=orchard" -var "image_name=orchard-$(Build.BuildId)" -var "app_package=gs://$(Packer.Project)-artifacts/Orchard.Web-$(Build.BuildId).zip" $(Build.SourcesDirectory)/packer.json'
